name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x' # This will use the latest version of Python 3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      # If you don't have a requirements.txt file, you can specify packages directly:
      # pip install pytest

    - name: Run tests
      run: pytest
      # If you're not using pytest, you can use Python's built-in unittest:
      # run: python -m unittest discover tests

