name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: v2 # Ensure you are using the latest v2 release

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20' # Update to Node.js version 20 or higher

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
